### ISSUE TITLE
Panic at first run

### ISSUE THREAD

**Issue by jvehent** [mozilla/libaudit-go#19]
While running the example code from [gsoc16](https://github.com/arunk-s/gsoc16), the program first panicked, the worked correctly the second time I ran it.

```
# ./main 
{"class":"log","parameters":"audit is enabled"}
{"class":"log","parameters":{"stack":[5447707,4758930,4756548,4559457]}}
panic: AuditSetPID failed: auditGetReply failed: error while parsing NetlinkMessage: Nlmsghdr header length unexpected 1936028448, actual packet length 16

goroutine 5 [running]:
panic(0x6bee60, 0xc420133bf0)
    /usr/lib/go/src/runtime/panic.go:500 +0x1a1
mig.ninja/mig/modules/audit.(*run).runAudit(0xc42007a280, 0xc42000d190, 0xc420026078, 0xc420026080, 0x815580, 0xc420133bf0)
    /tmp/gsoc16/vendor/src/mig.ninja/mig/modules/audit/audit.go:251 +0x415
created by mig.ninja/mig/modules/audit.(*run).Run
    /tmp/gsoc16/vendor/src/mig.ninja/mig/modules/audit/audit.go:144 +0x1f7
```

**Comment by ameihm0912** [comment]
This should be resolved now (fixed in 7c6747f), and was related to alignment issues processing incoming netlink packets.
